//base
exports.NO_ERROR = 'NO_ERROR';
exports.INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

//Registration
exports.REG_MANDATORY_FIELD = 'REG_MANDATORY_FIELD';
exports.REG_DUPLICATE_USERNAME = 'REG_DUPLICATE_USERNAME';
exports.REG_DUPLICATE_EMAIL = 'REG_DUPLICATE_EMAIL';
exports.REG_INVALID_EMAIL = 'REG_INVALID_EMAIL';
exports.REG_INVALID_USERNAME = 'REG_INVALID_USERNAME';
exports.REG_INVALID_PASSWORD = 'REG_INVALID_PASSWORD';