//base
exports.NO_ERROR = 'NO_ERROR';
exports.INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

//Registration
exports.REG_MANDATORY_FIELD = 'REG_MANDATORY_FIELD';
exports.REG_DUPLICATE_USERNAME = 'REG_DUPLICATE_USERNAME';
exports.REG_DUPLICATE_EMAIL = 'REG_DUPLICATE_EMAIL';
exports.REG_INVALID_EMAIL = 'REG_INVALID_EMAIL';
exports.REG_INVALID_USERNAME = 'REG_INVALID_USERNAME';
exports.REG_INVALID_PASSWORD = 'REG_INVALID_PASSWORD';
exports.REG_INVALID_CAPTCHA_TOKEN = 'REG_INVALID_CAPTCHA_TOKEN';

//Login
exports.SIGNIN_MANDATORY_FIELD  = 'SIGNIN_MANDATORY_FIELD';
exports.SIGNIN_INVALID_EMAIL    = 'SIGNIN_INVALID_EMAIL';
exports.SIGNIN_GRANT_TYPE_MANDATORY = 'SIGNIN_GRANT_TYPE_MANDATORY';
exports.SIGNIN_INVALID_CLIENT = 'SIGNIN_INVALID_CLIENT';